package vista;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.util.ArrayList;
import conexion.Conexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.sql.SQLException;

public class InterGraficaVentas extends javax.swing.JInternalFrame {

    ArrayList<Integer> listaCantidad = new ArrayList<>();
    ArrayList<String> listaFechas = new ArrayList<>();

    int cantidadResultados = 0;
    String[] vectorFechaVenta;
    int[] vectorStatusCantidad;

    //constructor
    public InterGraficaVentas() {
        initComponents();
        this.setSize(new Dimension(550, 650));
        this.setTitle("Historial de Ventas");
        this.MetodoContador();
        vectorFechaVenta = new String[cantidadResultados];
        vectorStatusCantidad = new int[cantidadResultados];
        this.MetodoAlmacenarDatos();

    }

    //Metodo para determinar la cantidad de resultado para graficar
    private int MetodoContador() {
        try {
            Connection cn = (Connection) Conexion.conectar();
            PreparedStatement pst = (PreparedStatement) cn.prepareStatement("select fechaVenta, count(fechaVenta) as Ventas from tb_cabecera_venta "
                    + "where fechaVenta BETWEEN'" + InterGraficas.fecha_inicio + "' and '" + InterGraficas.fecha_fin + "' group by fechaVenta;");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                cantidadResultados++;
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error en:" + e);
        }
        return cantidadResultados;
    }

    //metodo para almacenar los datos en los arraylist a graficar 
    private void MetodoAlmacenarDatos() {
        try {
            Connection cn = (Connection) Conexion.conectar();
            PreparedStatement pst = (PreparedStatement) cn.prepareStatement("select fechaVenta, count(fechaVenta) as Ventas from tb_cabecera_venta "
                    + "where fechaVenta BETWEEN '" + InterGraficas.fecha_inicio + "' and '" + InterGraficas.fecha_fin + "' group by fechaVenta;");
            ResultSet rs = pst.executeQuery();
            int contador = 0;
            while (rs.next()) {
                vectorFechaVenta[contador] = rs.getString("fechaVenta");
                vectorStatusCantidad[contador] = rs.getInt("Ventas");
                listaFechas.add(vectorFechaVenta[contador]);
                listaCantidad.add(vectorStatusCantidad[contador]);

                contador++;
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error en:" + e);
        }
    }

    //metodo para determinar cual es el dia de mayor ventas
    public int MetodoMayorVenta(ArrayList<Integer> listaCantidad) {
        int mayor = 0;
        for (int i = 0; i < listaCantidad.size(); i++) {
            if (listaCantidad.get(i) > mayor) {
                mayor = listaCantidad.get(i);
            }
        }
        return mayor;
    }
    
    //metodo para dibujar la grafica
    @Override
    public void paint(Graphics g) {
        super.paint(g);

        int mayorVenta = MetodoMayorVenta(listaCantidad);
        int largo_nuevoIngreso = 0;
        int parametro1 = 133;
        int parametroFecha = 118;
        int parametro3 = 100;

        for (int i = 0; i < listaCantidad.size(); i++) {
            largo_nuevoIngreso = listaCantidad.get(i) * 400 / mayorVenta;
            switch (i) {
                case 0:
                    g.setColor(new Color(140, 34, 75));
                    break;
                case 1:
                    g.setColor(new Color(255, 34, 0));
                    break;
                case 2:
                    g.setColor(new Color(140, 100, 100));
                    break;
                case 3:
                    g.setColor(new Color(190, 240, 75));
                    break;
                case 4:
                    g.setColor(new Color(90, 90, 0));
                    break;
                case 5:
                    g.setColor(new Color(20, 98, 32));
                    break;
                default:
                    g.setColor(new Color(244, 244, 0));
                    break;
            }
            g.fillRect(100, parametro3, largo_nuevoIngreso, 40);
            g.drawString(listaFechas.get(i), 10, parametroFecha);
            g.drawString("cantidad:" + listaCantidad.get(i), 10, parametro1);
            parametro1 += 50;
            parametroFecha += 50;
            parametro3 += 50;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historial de Ventas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
